// CarDealership.js
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import CarCard from './CarCard';
import Footer from './Footer';
import './NewCars.css';

const CarDealership = () => {
  const initialCars = [
    {
      id: 1,
      make: 'Toyota',
      model: 'Camry',
      year: 2022,
      price: 25000,
      miles: 2000,
      color: 'White',
      condition: 'Excellent',
      image: 'https://cfx-wp-images.imgix.net/2022/01/Toyota-Camry-TRD-Front-edited.jpg?auto=compress%2Cformat&fit=scale&h=576&ixlib=php-3.3.0&w=1024&wpsize=large&s=37bd7696cfb65d69f242135773223e4b',
      interiorColor: 'Beige',
      milesPerGallon: 28,
      drivetrain: 'Front-Wheel Drive',
      fuelType: 'Gasoline',
      engine: '2.5L 4-cylinder',
      transmission: 'Automatic',
    },
    {
      id: 2,
      make: 'Honda',
      model: 'Civic',
      year: 2021,
      price: 22000,
      miles: 15000,
      color: 'Grey',
      condition: 'Good',
      image: 'https://di-uploads-pod1.dealerinspire.com/hondaoflincoln/uploads/2020/09/2021-Civic-Hatch-on-sale.jpg',
      interiorColor: 'Black',
      milesPerGallon: 32,
      drivetrain: 'Front-Wheel Drive',
      fuelType: 'Gasoline',
      engine: '2.0L 4-cylinder',
      transmission: 'Automatic',
    },
    // Add information for the remaining cars
    {
      id: 3,
      make: 'Ford',
      model: 'Mustang',
      year: 2023,
      price: 35000,
      miles: 12000,
      color: 'Blue',
      condition: 'Like New',
      image: 'https://i.gaw.to/vehicles/photos/40/32/403228-2023-ford-mustang.jpg',
      interiorColor: 'Red',
      milesPerGallon: 25,
      drivetrain: 'Rear-Wheel Drive',
      fuelType: 'Gasoline',
      engine: '3.5L V6',
      transmission: 'Manual',
    },
    {
      id: 4,
      make: 'Chevrolet',
      model: 'Malibu',
      year: 2022,
      price: 28000,
      miles: 18000,
      color: 'White',
      condition: 'Excellent',
      image: 'https://smartcdn.gprod.postmedia.digital/driving/wp-content/uploads/2023/05/P2283718-scaled.jpg',
      interiorColor: 'Tan',
      milesPerGallon: 30,
      drivetrain: 'Front-Wheel Drive',
      fuelType: 'Gasoline',
      engine: '2.0L 4-cylinder',
      transmission: 'Automatic',
    },
    {
      id: 5,
      make: 'Nissan',
      model: 'Altima',
      year: 2021,
      price: 24000,
      miles: 22000,
      color: 'Red',
      condition: 'Good',
      image: 'https://editorials.autotrader.ca/media/194129/2021-nissan-altima-sr-awd-03-ct.jpg?anchor=center&mode=crop&width=1920&height=1080&rnd=132610125421730000g',
      interiorColor: 'Black',
      milesPerGallon: 27,
      drivetrain: 'Front-Wheel Drive',
      fuelType: 'Gasoline',
      engine: '2.5L 4-cylinder',
      transmission: 'Automatic',
    },
    {
        id: 6,
        make: 'BMW',
        model: 'X5',
        year: 2023,
        price: 50000,
        miles: 8000,
        color: 'Blue',
        condition: 'Excellent',
        image: 'url_to_x5_image.jpg',
        interiorColor: 'White',
        milesPerGallon: 24,
        drivetrain: 'All-Wheel Drive',
        fuelType: 'Gasoline',
        engine: '3.0L V6',
        transmission: 'Automatic',
      },
      {
        id: 7,
        make: 'Mercedes-Benz',
        model: 'C-Class',
        year: 2022,
        price: 45000,
        miles: 10000,
        color: 'Red',
        condition: 'Like New',
        image: 'url_to_cclass_image.jpg',
        interiorColor: 'Black',
        milesPerGallon: 28,
        drivetrain: 'Rear-Wheel Drive',
        fuelType: 'Gasoline',
        engine: '2.0L 4-cylinder',
        transmission: 'Automatic',
      },
      {
        id: 8,
        make: 'Audi',
        model: 'A4',
        year: 2023,
        price: 42000,
        miles: 3000,
        color: 'Black',
        condition: 'Excellent',
        image: 'url_to_a4_image.jpg',
        interiorColor: 'Brown',
        milesPerGallon: 26,
        drivetrain: 'All-Wheel Drive',
        fuelType: 'Gasoline',
        engine: '2.0L 4-cylinder',
        transmission: 'Automatic',
      },
      {
        id: 9,
        make: 'Tesla',
        model: 'Model 3',
        year: 2022,
        price: 60000,
        miles: 5000,
        color: 'White',
        condition: 'Good',
        image: 'url_to_model3_image.jpg',
        interiorColor: 'Black',
        milesPerGallon: 'Electric',
        drivetrain: 'All-Wheel Drive',
        fuelType: 'Electric',
        engine: 'Electric Motor',
        transmission: 'Automatic',
      },
      {
        id: 10,
        make: 'Hyundai',
        model: 'Sonata',
        year: 2021,
        price: 23000,
        miles: 16000,
        color: 'Silver',
        condition: 'Excellent',
        image: 'url_to_sonata_image.jpg',
        interiorColor: 'Grey',
        milesPerGallon: 29,
        drivetrain: 'Front-Wheel Drive',
        fuelType: 'Gasoline',
        engine: '2.5L 4-cylinder',
        transmission: 'Automatic',
      },

{
    id: 11,
    make: 'Kia',
    model: 'Optima',
    year: 2023,
    price: 26000,
    miles: 13000,
    color: 'Blue',
    condition: 'Good',
    image: 'url_to_optima_image.jpg',
    interiorColor: 'Beige',
    milesPerGallon: 27,
    drivetrain: 'Front-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '2.5L 4-cylinder',
    transmission: 'Automatic',
  },
  {
    id: 12,
    make: 'Subaru',
    model: 'Outback',
    year: 2022,
    price: 32000,
    miles: 9000,
    color: 'Red',
    condition: 'Like New',
    image: 'url_to_outback_image.jpg',
    interiorColor: 'Black',
    milesPerGallon: 26,
    drivetrain: 'All-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '2.4L 4-cylinder',
    transmission: 'Automatic',
  },
  {
    id: 13,
    make: 'Mazda',
    model: 'CX-5',
    year: 2021,
    price: 28000,
    miles: 7000,
    color: 'Black',
    condition: 'Excellent',
    image: 'url_to_cx5_image.jpg',
    interiorColor: 'Red',
    milesPerGallon: 28,
    drivetrain: 'Front-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '2.5L 4-cylinder',
    transmission: 'Automatic',
  },
  {
    id: 14,
    make: 'Volkswagen',
    model: 'Jetta',
    year: 2023,
    price: 25000,
    miles: 11000,
    color: 'White',
    condition: 'Good',
    image: 'url_to_jetta_image.jpg',
    interiorColor: 'Grey',
    milesPerGallon: 30,
    drivetrain: 'Front-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '1.4L 4-cylinder',
    transmission: 'Automatic',
  },
  {
    id: 15,
    make: 'Acura',
    model: 'MDX',
    year: 2022,
    price: 48000,
    miles: 14000,
    color: 'Silver',
    condition: 'Excellent',
    image: 'url_to_mdx_image.jpg',
    interiorColor: 'Brown',
    milesPerGallon: 23,
    drivetrain: 'All-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '3.5L V6',
    transmission: 'Automatic',
  },
  {
    id: 16,
    make: 'Lexus',
    model: 'RX',
    year: 2021,
    price: 52000,
    miles: 17000,
    color: 'Blue',
    condition: 'Like New',
    image: 'url_to_rx_image.jpg',
    interiorColor: 'Tan',
    milesPerGallon: 29,
    drivetrain: 'Front-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '3.5L V6',
    transmission: 'Automatic',
  },
  {
    id: 17,
    make: 'Buick',
    model: 'Encore',
    year: 2023,
    price: 30000,
    miles: 20000,
    color: 'Red',
    condition: 'Good',
    image: 'url_to_encore_image.jpg',
    interiorColor: 'Black',
    milesPerGallon: 25,
    drivetrain: 'Front-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '1.4L 4-cylinder',
    transmission: 'Automatic',
  },
  {
    id: 18,
    make: 'Jeep',
    model: 'Cherokee',
    year: 2022,
    price: 35000,
    miles: 25000,
    color: 'Black',
    condition: 'Excellent',
    image: 'url_to_cherokee_image.jpg',
    interiorColor: 'Grey',
    milesPerGallon: 24,
    drivetrain: 'Front-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '2.4L 4-cylinder',
    transmission: 'Automatic',
  },
  {
    id: 19,
    make: 'Ram',
    model: '1500',
    year: 2021,
    price: 40000,
    miles: 3000,
    color: 'White',
    condition: 'Good',
    image: 'url_to_ram1500_image.jpg',
    interiorColor: 'Brown',
    milesPerGallon: 22,
    drivetrain: 'Rear-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '5.7L V8',
    transmission: 'Automatic',
  },
  {
    id: 20,
    make: 'GMC',
    model: 'Terrain',
    year: 2023,
    price: 32000,
    miles: 8000,
    color: 'Silver',
    condition: 'Excellent',
    image: 'url_to_terrain_image.jpg',
    interiorColor: 'Black',
    milesPerGallon: 27,
    drivetrain: 'Front-Wheel Drive',
    fuelType: 'Gasoline',
    engine: '1.5L 4-cylinder',
    transmission: 'Automatic',
  },
  ];

  const [cars, setCars] = useState(initialCars);

  return (
    <div className="page-container">
      <h1>Lingle Dealers</h1>
      <h2>Available New Cars</h2>
      <Link to="/" className="back-button">Back to Home</Link>
      <div className="cards-container">
        {cars.map(car => (
          <CarCard key={car.id} car={car} />
        ))}
      </div>
      <Footer />
    </div>
  );
};

export default CarDealership;
